### ISSUE TITLE
怎么触发

### ISSUE THREAD

**Issue by zrhqaq** [ffreemt/nonebot-plugin-autohelp#1]

**Comment by ghost** [comment]
麻烦多看看下面介绍

**Comment by ffreemt** [comment]
``patt = re.compile(r"^[/!#]?\s*(?:help|menu|帮助|菜单|caidan|info)|[/#]i", re.I)``

群聊天里任何含 help 或 menu、帮助、菜单、caidan、info 的信息都会触发。

可在nonebot_plugin_autohelp.py的第29行修改。

**Comment by ghost** [comment]
好的感谢
